In [1]:
import pandas as pd
df = pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
df.head()          # first 5 rows
df.info()          # column types + non-null counts
df.describe()      # stats for numerical columns
df.isnull().sum()  # how many missing values in each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [2]:
df.head()          # first 5 rows
df.info()          # column types + non-null counts
df.describe()      # stats for numerical columns
df.isnull().sum()  # how many missing values in each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
df.head()          # first 5 rows
df.info()          # column types + non-null counts
df.describe()      # stats for numerical columns
df.isnull().sum()  # how many missing values in each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [7]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [16]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [17]:
df["Fare"] = df["Fare"].fillna(df["Fare"].median())

In [18]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [19]:
df.isnull().sum()   # should be all zeros now

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [20]:
df["Sex"] = df["Sex"].map({"male": 0, "female": 1})

In [21]:
df = pd.get_dummies(df, columns=["Embarked"], drop_first=True)

In [22]:
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1   # +1 for self

In [23]:
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)

In [24]:
from sklearn.preprocessing import StandardScaler

numeric_cols = ["Age", "Fare", "SibSp", "Parch", "FamilySize"]

scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [25]:
X = df.drop(columns=["Survived"])
y = df["Survived"]

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
print("Accuracy:", accuracy_score(y_val, y_pred))

Accuracy: 0.7988826815642458

In [28]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_val, y_pred))
print(classification_report(y_val, y_pred))

[[89 16]
 [20 54]]
              precision    recall  f1-score   support

           0       0.82      0.85      0.83       105
           1       0.77      0.73      0.75        74

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

In [31]:
test_df = pd.read_csv("test.csv")
test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [32]:
test_df.drop(["Cabin", "Ticket", "Name"], axis=1, inplace=True)

In [34]:
test_df["Age"] = test_df["Age"].fillna(test_df["Age"].median())
test_df["Embarked"] = test_df["Embarked"].fillna(test_df["Embarked"].mode()[0])
test_df["Fare"] = test_df["Fare"].fillna(test_df["Fare"].median())

In [35]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()
test_df["Sex"] = enc.fit_transform(test_df["Sex"])
test_df["Embarked"] = enc.fit_transform(test_df["Embarked"])

In [37]:
test_df = pd.get_dummies(test_df, columns=['Embarked'])

In [38]:
test_df['FamilySize'] = test_df['SibSp'] + test_df['Parch'] + 1
test_df['IsAlone'] = (test_df['FamilySize'] == 1).astype(int)

In [39]:
for col in ['Embarked_Q', 'Embarked_S']:
    if col not in test_df:
        test_df[col] = 0

In [40]:
test_df = test_df.drop(columns=['PassengerId', 'Embarked'], errors='ignore')

In [41]:
model_features = ['Pclass', 'Sex', 'Age', 'Fare', 'Embarked_Q', 'Embarked_S', 'FamilySize', 'IsAlone']

In [42]:
test_df = test_df[model_features]

In [44]:
test_df.columns

Index(['Pclass', 'Sex', 'Age', 'Fare', 'Embarked_Q', 'Embarked_S',
       'FamilySize', 'IsAlone'],
      dtype='object')

In [45]:
required_cols = ['Pclass', 'Sex', 'Age', 'Fare', 'Embarked_Q', 'Embarked_S', 'FamilySize', 'IsAlone']

for col in required_cols:
    if col not in test_df:
        test_df[col] = 0

test_df = test_df[required_cols]

In [47]:
model.feature_names_in_

array(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_Q',
       'Embarked_S', 'FamilySize', 'IsAlone'], dtype=object)

In [51]:
test_df = pd.read_csv("test.csv")
test_df = test_df.copy()

In [50]:
test_df = test_df.copy()

test_df['Age'] = test_df['Age'].fillna(test_df['Age'].median())
test_df['Fare'] = test_df['Fare'].fillna(test_df['Fare'].median())
test_df['Embarked'] = test_df['Embarked'].fillna(test_df['Embarked'].mode()[0])

In [53]:
test_df = pd.read_csv("test.csv")
test_df = test_df.copy()

In [54]:
test_df['Sex'] = test_df['Sex'].map({'male': 0, 'female': 1})

test_df['Age'] = test_df['Age'].fillna(test_df['Age'].median())
test_df['Fare'] = test_df['Fare'].fillna(test_df['Fare'].median())

test_df['Embarked'] = test_df['Embarked'].fillna(test_df['Embarked'].mode()[0])
test_df = pd.get_dummies(test_df, columns=['Embarked'], prefix='Embarked')

In [55]:
test_df['FamilySize'] = test_df['SibSp'] + test_df['Parch'] + 1
test_df['IsAlone'] = (test_df['FamilySize'] == 1).astype(int)

In [56]:
for col in ['Embarked_Q', 'Embarked_S']:
    if col not in test_df.columns:
        test_df[col] = 0

In [57]:
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
            'Embarked_Q', 'Embarked_S', 'FamilySize', 'IsAlone']

test_df = test_df[features]

In [58]:
test_pred = model.predict(test_df)
test_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [60]:
test_df_original = pd.read_csv("test.csv")

submission = pd.DataFrame({
    'PassengerId': test_df_original['PassengerId'],
    'Survived': test_pred
})

submission.to_csv("submission.csv", index=False)